/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Godspeed (https://sketchfab.com/godspeedx14)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-3d-model-asus-tuf-dash-f15-2022-4e80289a455f403fabe181211b10b98e
Title: LAPTOP 3D MODEL (Asus Tuf Dash F15 2022)
*/

import React, { JSX, useEffect, useMemo, useState } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { useThree } from "@react-three/fiber";
import {
  CanvasTexture,
  LinearFilter,
  LinearMipmapLinearFilter,
  Material,
  Mesh,
  MeshStandardMaterial,
  SRGBColorSpace,
  type Texture,
} from "three";

/** Formats as a desktop clock does — 24h, zero-padded, minute resolution. */
function formatClock(date: Date) {
  return {
    time: `${String(date.getHours()).padStart(2, "0")}:${String(
      date.getMinutes(),
    ).padStart(2, "0")}`,
    day: new Intl.DateTimeFormat("en", {
      weekday: "long",
      day: "numeric",
      month: "long",
    }).format(date),
  };
}

type GLTFResult = {
  nodes: Record<string, Mesh>;
  materials: Record<string, Material>;
};

type DemoComputerProps = JSX.IntrinsicElements["group"];

export const DemoComputer: React.FC<DemoComputerProps> = (props) => {
  const { nodes, materials } = useGLTF("/models/asus_tuf_f15.glb") as unknown as GLTFResult;

  /*
    The laptop screen carries the portrait, so the page needs no separate
    avatar. Suspends with the model inside the existing Suspense boundary.

    A dedicated asset rather than the 1254px source: useTexture fetches the raw
    file and bypasses next/image, so pointing this at the original downloaded
    1.9 MB for one screen.
  */
  const baseTexture = useTexture("/images/profile-screen.jpg") as Texture;
  const maxAnisotropy = useThree((state) => state.gl.capabilities.getMaxAnisotropy());

  // Minute resolution, like an OS clock. Ticking per second would mean a full
  // texture upload every second for a digit almost nobody reads.
  const [now, setNow] = useState<Date | null>(null);

  useEffect(() => {
    setNow(new Date());

    let timeout: ReturnType<typeof setTimeout>;

    const scheduleNextMinute = () => {
      const date = new Date();
      const msToNextMinute =
        (60 - date.getSeconds()) * 1000 - date.getMilliseconds();

      timeout = setTimeout(() => {
        setNow(new Date());
        scheduleNextMinute();
      }, msToNextMinute);
    };

    scheduleNextMinute();

    return () => clearTimeout(timeout);
  }, []);

  /*
    The wallpaper is composited rather than loaded flat: the portrait sits on
    the right of the source, so the empty left half carries a live clock. Baking
    a time into the JPEG would freeze it at whatever moment the file was made.
  */
  const screenTexture = useMemo(() => {
    const image = baseTexture.image as HTMLImageElement | undefined;

    if (!image?.width) return baseTexture;

    const canvas = document.createElement("canvas");
    canvas.width = image.width;
    canvas.height = image.height;

    const ctx = canvas.getContext("2d");

    if (!ctx) return baseTexture;

    ctx.drawImage(image, 0, 0, canvas.width, canvas.height);

    if (now) {
      const { time, day } = formatClock(now);
      const cx = canvas.width * 0.26;
      const cy = canvas.height * 0.46;

      ctx.textAlign = "center";
      ctx.textBaseline = "alphabetic";

      ctx.fillStyle = "rgba(238, 242, 246, 0.94)";
      ctx.font = `300 ${Math.round(canvas.height * 0.19)}px "Segoe UI", Helvetica, Arial, sans-serif`;
      ctx.fillText(time, cx, cy);

      ctx.fillStyle = "rgba(238, 242, 246, 0.58)";
      ctx.font = `400 ${Math.round(canvas.height * 0.042)}px "Segoe UI", Helvetica, Arial, sans-serif`;
      ctx.fillText(day, cx, cy + canvas.height * 0.075);
    }

    const texture = new CanvasTexture(canvas);
    texture.colorSpace = SRGBColorSpace;
    // Matches the source image orientation, which is already drawn top-left.
    texture.flipY = false;
    /*
      The screen is viewed at a yaw, so without anisotropic filtering the
      texture smears along the viewing angle and reads as blurry regardless of
      how large the source is.
    */
    texture.anisotropy = maxAnisotropy;
    texture.minFilter = LinearMipmapLinearFilter;
    texture.magFilter = LinearFilter;
    texture.generateMipmaps = true;
    texture.needsUpdate = true;

    return texture;
  }, [baseTexture, now, maxAnisotropy]);

  // Release the previous composite; without this each minute leaks a texture.
  useEffect(() => {
    return () => {
      if (screenTexture !== baseTexture) screenTexture.dispose();
    };
  }, [screenTexture, baseTexture]);

  useEffect(() => {
    /*
      material_13 is the wallpaper surface — the only material in the GLB that
      ships a baseColorTexture. display_sqr is the glass panel sitting over it,
      so texturing that one lights up the screen without showing any image.
    */
    const wallpaper = materials.material_13;

    if (!(wallpaper instanceof MeshStandardMaterial)) return;

    // Colour space, orientation and filtering are set on the composite itself.
    wallpaper.map = screenTexture;
    // White base so the portrait's own colours come through unmodulated.
    wallpaper.color.setScalar(1);
    /*
      Lit from within so it reads as a powered display, kept under Bloom's 0.8
      luminance threshold — higher values clip the panel to solid white.
    */
    wallpaper.emissiveMap = screenTexture;
    // Nudged up to hold readability against the lower tone-mapping exposure —
    // the display is now the brightest thing in the scene, which is how a
    // powered screen should behave in a dark room.
    wallpaper.emissive.setScalar(0.45);
    wallpaper.emissiveIntensity = 0.7;
    wallpaper.toneMapped = true;
    // roughness, metalness and envMapIntensity are set in the material_13 case
    // of applyPbrTuning, which runs after this effect and would overwrite them.
    wallpaper.needsUpdate = true;
  }, [materials, screenTexture]);

  useEffect(() => {
    const applyPbrTuning = (materialName: string, material: Material) => {
      if (!(material instanceof MeshStandardMaterial)) {
        return;
      }

      // Baseline environment response. Was 1.45, which made the HDR read as a
      // bank of studio lights across every glossy surface.
      material.envMapIntensity = 0.6;
      material.roughness ??= 0.7;
      material.metalness ??= 0.15;

      switch (materialName) {
        case "DECK":
        case "DECK.001":
          material.color.offsetHSL(0, -0.02, -0.03);
          material.metalness = 0.72;
          material.roughness = 0.28;
          break;
        case "material":
        case "material_7":
          material.metalness = 0.58;
          material.roughness = 0.34;
          break;
        case "KEYS":
        case "wasd_key":
        case "power_button":
          material.metalness = 0.08;
          material.roughness = 0.78;
          break;
        case "display_sqr":
          material.metalness = 0.02;
          material.roughness = 0.22;
          material.envMapIntensity = 0.12;
          material.emissive.setScalar(0.03);
          break;
        case "material_13":
          /*
            Screen panel. The map and emissive are owned by the portrait effect
            above; the optical response is set here because the block before
            this switch applies envMapIntensity 1.45 to every material, which
            let the HDR reflect across the display at full strength.

            Near-matte on purpose: at roughness 0.5 the 48-intensity key light
            landed as a blown specular hotspot. A real matte LCD scatters that
            into a faint even sheen instead of a mirror highlight.
          */
          material.envMapIntensity = 0.06;
          material.roughness = 0.94;
          material.metalness = 0;
          break;
        case "tuf_logo":
        case "ASUS_LOGO":
        case "outer_logo":
          material.metalness = 0.82;
          // Still the most reflective parts of the model, but roughened and
          // pulled down from 1.9 so they read as brushed metal rather than
          // mirrors picking up the environment.
          material.roughness = 0.38;
          material.envMapIntensity = 0.85;
          break;
        case "keyLight":
          material.metalness = 0;
          material.roughness = 0.18;
          material.emissive.copy(material.color).multiplyScalar(0.65);
          material.toneMapped = false;
          break;
        default:
          break;
      }

      material.needsUpdate = true;
    };

    Object.entries(materials).forEach(([materialName, material]) => {
      applyPbrTuning(materialName, material as Material);
    });
  }, [materials]);

  return (
    <group {...props} dispose={null}>
      <group position={[-2.302, 0, 0.011]} scale={[0.463, 0.024, 0.645]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.DECK} />
        <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials.deck2} />
        <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials.pendrive} />
        <mesh castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials.material} />

        <group
          position={[-0.001, 1.102, 0.679]}
          rotation={[Math.PI, Math.PI / 2, 0]}
          scale={[-0.041, 0.088, 0.057]}
        >
          <mesh castShadow receiveShadow geometry={nodes.Object_9.geometry} material={materials.KEYS} />
          <mesh castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials.wasd_key} />
        </group>

        <group position={[-0.706, 1.045, -0.934]} scale={[0.036, 0.026, 0.026]}>
          <mesh castShadow receiveShadow geometry={nodes.Object_20.geometry} material={materials.power_button} />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_22.geometry}
            material={materials.material_7}
            position={[-0.254, 1.368, -0.004]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[12.048, 1609.138, 57.751]}
          />
        </group>

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials.DECK}
          position={[-0.977, -0.059, -0.116]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[1, 1.167, 1]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials["DECK.001"]}
          position={[-0.91, 0.285, -0.625]}
          scale={[2.161, 45.815, 0.787]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16.geometry}
          material={materials["DECK.001"]}
          position={[-0.91, 0.296, 0.653]}
          scale={[2.161, 45.815, 0.787]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_18.geometry}
          material={materials.material_7}
          position={[-0.917, 1.045, -0.002]}
          scale={[2.161, 41.868, 1.551]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_24.geometry}
          material={materials.tuf_logo}
          position={[0.492, 0.898, -0.097]}
          scale={[-2.161, 41.868, 1.551]}
        />
      </group>

      <group position={[-2.428, 0.03, 0.43]} rotation={[0, 1.571, 0]} scale={[0.039, 0.024, 0.032]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_26.geometry} material={materials.DECK} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_28.geometry}
          material={materials.DECK}
          position={[-1.498, -0.016, 2.039]}
          scale={[0.652, 0.652, 0.785]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_30.geometry}
          material={materials.DECK}
          position={[2.033, 0.003, 2.066]}
          scale={[0.294, 0.294, 0.354]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_32.geometry}
          material={materials.DECK}
          position={[0.229, -0.004, 2.073]}
          scale={[0.371, 0.371, 0.447]}
        />
      </group>

      <group
        position={[-2.734, 0.008, 0.655]}
        rotation={[0, 0, -1.136]}
        scale={[-0.762, 0.008, 0.762]}
      >
        <mesh castShadow receiveShadow geometry={nodes.Object_34.geometry} material={materials.DECK} />
        <mesh castShadow receiveShadow geometry={nodes.Object_35.geometry} material={materials.display_sqr} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_37.geometry}
          material={materials.DECK}
          position={[0, 1.111, -0.029]}
          rotation={[1.571, -1.571, 0]}
          scale={[-100.103, 1.441, 1.005]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_39.geometry}
          material={materials.DECK}
          position={[0, 1.111, -1.668]}
          rotation={[1.571, -1.571, 0]}
          scale={[-100.103, 1.441, 1.005]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_41.geometry}
          material={materials.ASUS_LOGO}
          position={[0.133, -2.677, -0.77]}
          rotation={[0, 0, -0.231]}
          scale={[-1.472, 130.758, 1.313]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_43.geometry}
          material={materials.outer_logo}
          position={[0.992, -3.737, -0.305]}
          rotation={[-3.142, 0, -0.132]}
          scale={[1.982, 162.831, 1.718]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_45.geometry}
          material={materials.material_13}
          position={[0.699, -3.434, -0.852]}
          rotation={[-1.566, -1.562, -1.557]}
          scale={[-0.948, 94.428, 1.008]}
        />
      </group>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_47.geometry}
        material={materials.keyLight}
        position={[-2.42, 0.02, 0.005]}
        scale={[0.229, 0.346, 0.625]}
      />
    </group>
  );
};

useGLTF.preload("/models/asus_tuf_f15.glb");
