/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Godspeed (https://sketchfab.com/godspeedx14)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-3d-model-asus-tuf-dash-f15-2022-4e80289a455f403fabe181211b10b98e
Title: LAPTOP 3D MODEL (Asus Tuf Dash F15 2022)
*/

import React, { JSX, useEffect } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import {
  Material,
  Mesh,
  MeshStandardMaterial,
  SRGBColorSpace,
  type Texture,
} from "three";

type GLTFResult = {
  nodes: Record<string, Mesh>;
  materials: Record<string, Material>;
};

type DemoComputerProps = JSX.IntrinsicElements["group"];

export const DemoComputer: React.FC<DemoComputerProps> = (props) => {
  const { nodes, materials } = useGLTF("/models/asus_tuf_f15.glb") as unknown as GLTFResult;

  /*
    The laptop screen carries the portrait, so the page needs no separate
    avatar. Suspends with the model inside the existing Suspense boundary.

    Deliberately a dedicated 512px asset: useTexture fetches the raw file and
    bypasses next/image, so pointing this at the 1254px source downloaded
    1.9 MB for a screen a couple of hundred pixels wide.
  */
  const screenTexture = useTexture("/images/profile-screen.jpg") as Texture;

  useEffect(() => {
    /*
      material_13 is the wallpaper surface — the only material in the GLB that
      ships a baseColorTexture. display_sqr is the glass panel sitting over it,
      so texturing that one lights up the screen without showing any image.
    */
    const wallpaper = materials.material_13;

    if (!(wallpaper instanceof MeshStandardMaterial)) return;

    screenTexture.colorSpace = SRGBColorSpace;
    // Match the glTF UV convention the original wallpaper was authored against.
    screenTexture.flipY = false;
    screenTexture.needsUpdate = true;

    wallpaper.map = screenTexture;
    // White base so the portrait's own colours come through unmodulated.
    wallpaper.color.setScalar(1);
    /*
      Lit from within so it reads as a powered display, kept under Bloom's 0.8
      luminance threshold — higher values clip the panel to solid white.
    */
    wallpaper.emissiveMap = screenTexture;
    wallpaper.emissive.setScalar(0.35);
    wallpaper.emissiveIntensity = 0.6;
    wallpaper.metalness = 0;
    wallpaper.roughness = 0.5;
    wallpaper.toneMapped = true;
    wallpaper.needsUpdate = true;
  }, [materials, screenTexture]);

  useEffect(() => {
    const applyPbrTuning = (materialName: string, material: Material) => {
      if (!(material instanceof MeshStandardMaterial)) {
        return;
      }

      material.envMapIntensity = 1.45;
      material.roughness ??= 0.7;
      material.metalness ??= 0.15;

      switch (materialName) {
        case "DECK":
        case "DECK.001":
          material.color.offsetHSL(0, -0.02, -0.03);
          material.metalness = 0.72;
          material.roughness = 0.28;
          break;
        case "material":
        case "material_7":
          material.metalness = 0.58;
          material.roughness = 0.34;
          break;
        case "KEYS":
        case "wasd_key":
        case "power_button":
          material.metalness = 0.08;
          material.roughness = 0.78;
          break;
        case "display_sqr":
          material.metalness = 0.02;
          material.roughness = 0.22;
          material.envMapIntensity = 0.12;
          material.emissive.setScalar(0.03);
          break;
        case "material_13":
          // Owned by the portrait texture effect above.
          break;
        case "tuf_logo":
        case "ASUS_LOGO":
        case "outer_logo":
          material.metalness = 0.82;
          material.roughness = 0.24;
          material.envMapIntensity = 1.9;
          break;
        case "keyLight":
          material.metalness = 0;
          material.roughness = 0.18;
          material.emissive.copy(material.color).multiplyScalar(0.65);
          material.toneMapped = false;
          break;
        default:
          break;
      }

      material.needsUpdate = true;
    };

    Object.entries(materials).forEach(([materialName, material]) => {
      applyPbrTuning(materialName, material as Material);
    });
  }, [materials]);

  return (
    <group {...props} dispose={null}>
      <group position={[-2.302, 0, 0.011]} scale={[0.463, 0.024, 0.645]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.DECK} />
        <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials.deck2} />
        <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials.pendrive} />
        <mesh castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials.material} />

        <group
          position={[-0.001, 1.102, 0.679]}
          rotation={[Math.PI, Math.PI / 2, 0]}
          scale={[-0.041, 0.088, 0.057]}
        >
          <mesh castShadow receiveShadow geometry={nodes.Object_9.geometry} material={materials.KEYS} />
          <mesh castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials.wasd_key} />
        </group>

        <group position={[-0.706, 1.045, -0.934]} scale={[0.036, 0.026, 0.026]}>
          <mesh castShadow receiveShadow geometry={nodes.Object_20.geometry} material={materials.power_button} />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_22.geometry}
            material={materials.material_7}
            position={[-0.254, 1.368, -0.004]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[12.048, 1609.138, 57.751]}
          />
        </group>

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials.DECK}
          position={[-0.977, -0.059, -0.116]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[1, 1.167, 1]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials["DECK.001"]}
          position={[-0.91, 0.285, -0.625]}
          scale={[2.161, 45.815, 0.787]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16.geometry}
          material={materials["DECK.001"]}
          position={[-0.91, 0.296, 0.653]}
          scale={[2.161, 45.815, 0.787]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_18.geometry}
          material={materials.material_7}
          position={[-0.917, 1.045, -0.002]}
          scale={[2.161, 41.868, 1.551]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_24.geometry}
          material={materials.tuf_logo}
          position={[0.492, 0.898, -0.097]}
          scale={[-2.161, 41.868, 1.551]}
        />
      </group>

      <group position={[-2.428, 0.03, 0.43]} rotation={[0, 1.571, 0]} scale={[0.039, 0.024, 0.032]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_26.geometry} material={materials.DECK} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_28.geometry}
          material={materials.DECK}
          position={[-1.498, -0.016, 2.039]}
          scale={[0.652, 0.652, 0.785]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_30.geometry}
          material={materials.DECK}
          position={[2.033, 0.003, 2.066]}
          scale={[0.294, 0.294, 0.354]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_32.geometry}
          material={materials.DECK}
          position={[0.229, -0.004, 2.073]}
          scale={[0.371, 0.371, 0.447]}
        />
      </group>

      <group
        position={[-2.734, 0.008, 0.655]}
        rotation={[0, 0, -1.136]}
        scale={[-0.762, 0.008, 0.762]}
      >
        <mesh castShadow receiveShadow geometry={nodes.Object_34.geometry} material={materials.DECK} />
        <mesh castShadow receiveShadow geometry={nodes.Object_35.geometry} material={materials.display_sqr} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_37.geometry}
          material={materials.DECK}
          position={[0, 1.111, -0.029]}
          rotation={[1.571, -1.571, 0]}
          scale={[-100.103, 1.441, 1.005]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_39.geometry}
          material={materials.DECK}
          position={[0, 1.111, -1.668]}
          rotation={[1.571, -1.571, 0]}
          scale={[-100.103, 1.441, 1.005]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_41.geometry}
          material={materials.ASUS_LOGO}
          position={[0.133, -2.677, -0.77]}
          rotation={[0, 0, -0.231]}
          scale={[-1.472, 130.758, 1.313]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_43.geometry}
          material={materials.outer_logo}
          position={[0.992, -3.737, -0.305]}
          rotation={[-3.142, 0, -0.132]}
          scale={[1.982, 162.831, 1.718]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_45.geometry}
          material={materials.material_13}
          position={[0.699, -3.434, -0.852]}
          rotation={[-1.566, -1.562, -1.557]}
          scale={[-0.948, 94.428, 1.008]}
        />
      </group>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_47.geometry}
        material={materials.keyLight}
        position={[-2.42, 0.02, 0.005]}
        scale={[0.229, 0.346, 0.625]}
      />
    </group>
  );
};

useGLTF.preload("/models/asus_tuf_f15.glb");
